name: 'Terraform State Unlock'

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: 'Terraform Lock ID to unlock'
        required: true
        type: string
      environment:
        description: 'Environment to unlock'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

env:
  TF_VERSION: '1.3.8'

  # Snowflake
  TF_VAR_snowflake_organization_name: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
  TF_VAR_snowflake_account_name: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
  TF_VAR_snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
  TF_VAR_snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
  TF_VAR_default_password: ${{ secrets.DEFAULT_PASSWORD }}

jobs:
  unlock-state:
    name: 'Unlock Terraform State'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Setup AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{secrets.ASSUME_ROLE_ARN}}
        aws-region: ap-northeast-1

    - name: Terraform Init
      run: terraform init -upgrade 
      working-directory: ./environments/${{ inputs.environment }}

    - name: Terraform Unlock State
      run: terraform force-unlock -force ${{ inputs.lock_id }}
      working-directory: ./environments/${{ inputs.environment }}
